### ISSUE TITLE
Tools don’t use the document language

### ISSUE THREAD

**Issue by chris-morgan** [hacklily/hacklily#3]
I always use `\language "english"`, but tools like Change Key Signature don’t respect that, still writing `fis` and `ges` for F♯ and G♭ rather than `fs` and `gf`.

See define-note-names.scm for the current supported languages and how to write notes in that language. Here’s a simple regular expression for detecting the language: `/\\language "(nederlands|catalan|deutsch|english|espanol|italiano|norsk|portugues|suomi|svenska|vlaams)"/`.

**Comment by jnetterf** [comment]
Good point. Moving to https://github.com/hacklily/makelily/issues/1.
