### ISSUE TITLE
Reduce risk of having a large GitHub scope on the client

### ISSUE THREAD

**Issue by jnetterf** [hacklily/hacklily#6]

**Comment by jnetterf** [comment]
We can:
 - restrict it to public repos
 - exchange it for a deploy key (doesn't make the modal any less scarier, but reduces our risk): e.g., https://www.netlify.com/docs/github-permissions/
 - not use GitHub

**Comment by lyndsysimon** [comment]
I'm unfortunately aware of the permissions issues through the GitHub API. :(

I would be a lot more comfortable with this is if requested access to public repositories only. That still wouldn't make me feel warm and fuzzy about it, but it would allow me to use it - as it is, I'm not willing to grant read access to the private repositories to which I have access. Some of those repositories belong to my employer, for instance.

**Comment by jnetterf** [comment]
Thanks for the feedback. My plan is to reduce it to public. Also, as soon as I get permission, I’m going to try replacing it with a repo-specific deploy key. I’ll try to tackle that this weekend.
