### ISSUE TITLE
hacklily.org gives "invalid version" error

### ISSUE THREAD

**Issue by ppmnt** [hacklily/hacklily#72]
![Screenshot 2024-10-24 12 26 22](https://github.com/user-attachments/assets/05ae295e-c4b1-4c13-a941-336bf0cdf1a5)

Visiting hacklily.org results in this error. Tried on ChromeOS and Mac, including in incognito window (i.e. no add-ons). This prevents any use of hacklily.org at the moment.

**Comment by jocelyn-stericker** [comment]
Thank you for reporting, this should be resolved.
